config/routes.rb
Rails.application.routes.draw do

   root 'test_sets#index'

   resources :test_sets, only: [:index, :show, :new, :create]
   resources :regressions, only: [:show, :new, :create]

   resources :test_items, only: [:new, :create]
   get '/update_regressions', to: 'test_items#update_regressions'

   resources :users, only: [:index, :show, :update, :destroy]
   get  'register', to: 'users#new'
   post 'register', to: 'users#create'

   get  'login',  to: 'sessions#new'
   post 'login',  to: 'sessions#create'
   get  'logout', to: 'sessions#destroy'
end

app/models/regression.rb
class Regression < ActiveRecord::Base
  belongs_to :test_set
  has_many :test_items, -> { order("vectorname") }
  has_many :pass_test_items, -> { where(status: 'pass') }, class_name: 'TestItem'
  has_many :fail_test_items, -> { where(status: 'fail') }, class_name: 'TestItem'
  has_many :hang_test_items, -> { where(status: 'hang') }, class_name: 'TestItem'
  has_many :not_test_test_items, ->  { where(status: 'not test') }, class_name: 'TestItem'

  delegate :name, to: :test_set, prefix: true
end

app/models/test_item.rb
require 'csv'

class TestItem < ActiveRecord::Base
  def self.import(file, regression_id)
    CSV.foreach(file.path, headers: true) do |row|
      row = row.to_hash
      row['status'].downcase!
      test_item = find_by(vectorname: row['vectorname'], regression_id: regression_id) || new
      test_item.update_attributes(row.merge({regression_id: regression_id}))
    end
  end
end

app/models/test_set.rb
class TestSet < ActiveRecord::Base
  validates_presence_of :name
  has_many :regressions, -> { order('created_at DESC') }
  has_many :recent_regressions,  -> { order('created_at DESC').limit(5) }, class_name: 'Regression'

  scope :recent, -> { order('updated_at DESC') }
end

app/models/user.rb
class User < ActiveRecord::Base

  validates_presence_of :name

  has_secure_password
  validates :password, length: { minimum: 5 }
  validates_confirmation_of :password
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged?

  def logged?
    true
  end
end

app/controllers/concerns/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end

  def destroy
  end
end

app/controllers/regressions_controller.rb
class RegressionsController < ApplicationController

  def show
    @regression = Regression.find params[:id]
    # @test_items = @regression.test_items.page(params[:page])
    respond_to do |format|
      format.html
      format.json { render json: TestItemDatatable.new(view_context) }
    end
  end

  def new
    @regression = Regression.new
  end

  def create
    regression = Regression.new regression_params
    if regression.save
      flash[:success] = "A regression has been created!"
      redirect_to regressions_path
    else
      flash[:danger] = "Something wrong when create!"
      redirect_to new_regression_path
    end
  end

  private
  def regression_params
    params.require(:regression).permit([:name, :description, :test_set_id])
  end

end

app/controllers/sessions_controller.rb
class SessionController < ApplicationController
  def new
  end

  def create
  end

  def destroy
    session[:user_id] = nil
  end
end

app/controllers/test_items_controller.rb
class TestItemsController < ApplicationController

  def show
  end

  def new
    @test_sets = TestSet.recent
    @regressions = TestSet.recent.first.regressions
  end

  def create
    if regression = Regression.find(params[:regression_id])
      TestItem.import(params[:logfile], regression.id)
      redirect_to regression
    else
      flash[:danger] = "Can't find that regression!"
      redirect_to :new
    end
  end

  def update_regressions
    test_set = TestSet.find(params[:test_set_id])
    @regressions = test_set.regressions
    respond_to do |format|
      format.js
    end
  end

end

app/controllers/test_sets_controller.rb
class TestSetsController < ApplicationController

  def index
    @test_sets = TestSet.page(params[:page]).per(5)
  end

  def show
    @test_set = TestSet.find params[:id]
    @regressions = @test_set.regressions.page params[:page]
  end

  def new
    @test_set = TestSet.new
  end

  def create
    @test_set = TestSet.new(params.require(:test_set).permit(:name))
    if @test_set.save
      flash[:success] = "A test set has been created!"
      redirect_to test_sets_path
    else
      flash[:danger] = "Something wrong when create!"
      redirect_to new_test_set_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en-US")
  %head
    %title FPGA Regression Logger
    %meta(charset="UTF-8")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    = csrf_meta_tags
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag "application"
    = yield :head
  %body
    %header
      = render 'shared/header'
    %section.content
      = render 'shared/messages'
      = yield
      %hr
    %footer.footer
      .container
        &copy 2014 Regression Logger

app/views/regressions/_regression.html.haml
%table.table#regressions-table
  %thead
    %tr
      %th Name
      %th Total
      %th Pass
      %th Fail
      %th Hang
      %th Not Test
      %th Description
  %tbody
    -regressions.each do |regression|
      %tr
        %td= link_to regression.name, regression
        %td#total=regression.test_items.size
        %td#pass=regression.pass_test_items.size
        %td#fail=regression.fail_test_items.size
        %td#hang=regression.hang_test_items.size
        %td#not_test=regression.not_test_test_items.size
        %td=regression.description

app/views/regressions/new.html.haml
%section.regression-new
  .container
    =form_for @regression, html: {class: "form-horizontal"} do |f|
      .form-group
        =f.label :name, class: "control-label col-md-1"
        .col-md-3
          =f.text_field :name, class: "form-control"
      .form-group
        =f.label :description, class: "control-label col-md-1"
        .col-md-3
          =f.text_field :description, class: "form-control"
      .form-group
        =f.label :test_set, class: "control-label col-md-1"
        .col-md-3
          =f.collection_select(:test_set_id, TestSet.all, :id, :name, {}, class: "form-control")
      .form-group
        .col-md-offset-1.col-md-3
          =f.submit 'New Regression', class: "btn btn-default"

app/views/regressions/show.html.haml
-content_for :head do
  -# %script(type="text/javascript" src="/assets/g.pie-min.js")
  -# %script(type="text/javascript" src="/assets/regression_pie.js")
  =javascript_include_tag "g.pie-min"
  =javascript_include_tag "regression_pie"
  =javascript_include_tag "test_item_table"
%section.regression-show
  .container
    .row.regression.panel.panel-default
      .panel-heading= "Test Set: #{@regression.test_set_name}, Regression: #{@regression.name}"
      .contents.panel-body
        #key-value
          Total:
          =@regression.test_items.size
          Pass:
          %span#pass
            =@regression.pass_test_items.size
          Fail:
          %span#fail
            =@regression.fail_test_items.size
          Hang:
          %span#hang
            =@regression.hang_test_items.size
          Not Test:
          %span#not_test
            =@regression.not_test_test_items.size
        %p= "Description: #{@regression.description}"
      #holder
    .row.test_items
      -# =paginate @test_items
      %table.table#test_item_table(data-source="#{regression_path(@regression, format: :json)}")
        %thead
          %th Vector Name
          %th Status
          %th Fail/Hang Frame No.
        %tbody
          -# -@test_items.each do |test_item|
          -#   %tr
          -#     %td= test_item.vectorname
          -#     %td= test_item.status
          -#     %td= test_item.frame_number

app/views/shared/_header.html.haml
%section#top-header.row
  %nav.navbar.navbar-inverse.navbar-fixed-top
    .container
      .navbar-header
        = link_to "FPGA Regression Logger", root_path, class: "navbar-brand"
      .navbar-collapse.collapse
        %ul.nav.navbar-nav
          %li.dropdown
            %a(href="#" class="dropdown-toggle" data-toggle="dropdown")
              Test Sets
              %span.caret
            %ul.dropdown-menu(role="menu")
              -TestSet.recent.each do |test_set|
                %li= link_to "#{test_set.name}", test_set
          - if logged?
            %li= link_to "New Test Set", new_test_set_path
            %li= link_to "New Regression", new_regression_path
            %li= link_to "Import", new_test_item_path

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/test_items/new.html.haml
-content_for :head do
  -# %script(type="text/javascript" src="/assets/import.js")
  =javascript_include_tag "import"
%section.test_items_new
  .container
    =form_tag test_items_path, class: "form-horizontal", multipart: true do
      .form-group
        =label_tag :test_set_id, "Test Set", class: "control-label col-md-1"
        .col-md-3
          =select_tag :test_set_id, options_for_select(@test_sets.map {|el| [el.name, el.id]}, 0), class: 'form-control'
      .form-group
        =label_tag :regression_id, "Regression", class: "control-label col-md-1"
        .col-md-3
          =select_tag :regression_id, options_for_select(@regressions.map {|el| [el.name, el.id]}, 0), class: 'form-control'
      .form-group
        =label_tag :logfile, "Log File", class: "control-label col-md-1"
        .col-md-3
          =file_field_tag :logfile, class: 'form-control'
      .form-group
        .col-md-offset-1.col-md-3
          =submit_tag 'Import', class: "btn btn-default"

app/views/test_items/update_regressions.js.erb
<%- options = @regressions.map { |regression| "<option value=#{regression.id}>#{regression.name}</option>" } %>
<%- option_text = options.join('') %>
$("#regression_id").empty().append("<%= option_text.html_safe %>")

app/views/test_sets/index.html.haml
%section.test_sets_index
  .container
    .alert.alert-success.alert-dismissible(role="alert")
      %button.close(data-dismiss="alert")
        %span(aria-hidden="true")x
        %span.sr-only Close
      %p
        欢迎来到
        %a(href="http://ke-pan.github.io/resume_cn.html")我
        的展示项目。此项目仍在开发中。点击
        %a(href="https://github.com/ke-pan/regression_logger")这里
        查看源码。
      %p 这是一个回归测试结果记录网页，特点是：
      %ul
        %li 上传 log 文件存储测试结果
        %li 测试结果可视化
        %li 动态表格
    =paginate @test_sets
    - @test_sets.each do |test_set|
      .row.test_sets
        %h3= test_set.name
        =render partial: "regressions/regression", locals: {regressions: test_set.recent_regressions}
        .row
          -# =link_to 'Add a new regression', new_regression_path, class: "col-md-3"
          =link_to 'more...', test_set, class: "col-md-3"

app/views/test_sets/new.html.haml
%section.test_sets_new
  .container
    =form_for @test_set, html: {class: "form-horizontal"} do |f|
      .form-group
        =f.label :name, class: "control-label col-md-1"
        .col-md-3
          =f.text_field :name, class: "form-control"
        .col-md-2
          =f.submit 'New Test Set', class: "btn btn-default"

app/views/test_sets/show.html.haml
-content_for :head do
  =javascript_include_tag "g.bar-min"
  =javascript_include_tag "regressions_bar"
  -# =javascript_include_tag "regressions_table"

%section.test_sets_show
  .container
    .row
      %h3= @test_set.name
      .regressions
        =paginate @regressions
        =render partial: "regressions/regression", locals: {regressions: @regressions}
        #holder